server:
  port: 80
  servlet:
    context-path: /girl
cupSize: C
age: 18
content: "cupSize:${cupSize},age:${age}"
boy:
  height: 180cm
  weight: 50kg
jdbc.url: jdbc:mysql://127.0.0.1:3306/girl?useUnicode=true&characterEncoding=utf8
jdbc.username: root
jdbc.password: root
jdbc.driver: com.mysql.jdbc.Driver
mybatis_config_file: mybaits-config.xml
mapper_path: /com/sdw/**/mapper/*.xml
entity_package: com.sdw.entity
# thymeleaf 静态资源配置
spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: utf-8
    servlet:
      content-type: text/html
    # 关闭缓存,即使刷新,上线环境改为true
    cache: false
 #REDIS配置
  redis:
  #数据库索引（默认0）
    database: 1
  #服务器ID地址
    host: 127.0.0.1
  #连接端口
    port: 6379
  #连接密码（默认为空）
    password:
    jedis:
      pool:
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 100
        #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 1
        #连接池中的最大空闲连接
        max-idle: 10
        #连接池中的最小空闲连接
        min-idle: 2
        #连接超时时间（毫秒）
        timeout: 0
  mvc:
  #设定静态文件路径 js,css等
    static-path-pattern: /static/**


