server:
  port: 80
  servlet:
    context-path: /girl
cupSize: C
age: 18
content: "cupSize:${cupSize},age:${age}"
boy:
  height: 180cm
  weight: 50kg
jdbc.url: jdbc:mysql://localhost:3306/girl?useUnicode=true&characterEncoding=utf8
jdbc.username: root
jdbc.password: root
jdbc.driver: com.mysql.jdbc.Driver
mybatis_config_file: mybaits-config.xml
mapper_path: /daoMapper/**.xml
entity_package: com.sdw.entity